package vehiclerentalsystem.GUI;

import java.util.List;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.BoxLayout;
import javax.swing.Box;

import vehiclerentalsystem.Controllers.VehicleController;
import vehiclerentalsystem.Controllers.CustomerController;
import vehiclerentalsystem.Controllers.BookingController;
import vehiclerentalsystem.Controllers.UserController;
import vehiclerentalsystem.Models.Vehicle;
import vehiclerentalsystem.Models.User;
import vehiclerentalsystem.Models.Customer;
import vehiclerentalsystem.Models.Booking;
import vehiclerentalsystem.GUI.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.JScrollPane;

public class EmployeeDashboard extends javax.swing.JFrame {

	private Class<?> currentFrame;
	private VehicleController vehicleController;
	private CustomerController customerController;
	private BookingController bookingController;
	private UserController userController;
	private JPanel cardsPanel;
	private User currentUser;

	public EmployeeDashboard(User user) {
		this.currentUser = user;
		this.vehicleController = new VehicleController();
		this.customerController = new CustomerController();
		this.bookingController = new BookingController();
		this.userController = new UserController();
		initComponents();
		currentFrame = this.getClass();
		updateAvailableVehiclesCount();
		updateRentedCarsCount();
		updateCustomersCount();

		// Update welcome message with user's name
		if (user != null) {
			jLabel3.setText("Welcome Back, " + user.getFirstName() + "!");
		}
	}

	// Default constructor for compatibility
	public EmployeeDashboard() {
		this(null);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Rental Employee Dashboard");
        setPreferredSize(new java.awt.Dimension(1200, 800));

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 0));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\sport-car (2).png")); // NOI18N
        jLabel1.setText(" CarRental Employee");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 5));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        Dashboard.setBackground(new java.awt.Color(0, 0, 0));
        Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\house (2).png")); // NOI18N
        Dashboard.setText(" DashBoard");
        Dashboard.setBorderPainted(false);
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\sport-car (2).png")); // NOI18N
        jButton2.setText(" Car Management");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\accountant (1).png")); // NOI18N
        jButton3.setText(" Booking");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\settings (1).png")); // NOI18N
        jButton4.setText(" Payment");
        jButton4.setBorderPainted(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
                sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGroup(sidebarPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jPanel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(sidebarPanelLayout
                                                .createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(Dashboard,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        174,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(sidebarPanelLayout
                                                .createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(sidebarPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                215,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton2,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                206,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                sidebarPanelLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(6, 6, 6)
                                                                        .addComponent(jButton3)))))
                                .addContainerGap(21, Short.MAX_VALUE)));
        sidebarPanelLayout.setVerticalGroup(
                sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(Dashboard,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Welcome Back, Employee!");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Here's what's happening with your car rental business today");

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Profile");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\manager (1).png")); // NOI18N
        jLabel5.setText("Employee");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4))
                                                .addContainerGap(
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout
                                                .createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        413,
                                                        Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addGap(54, 54, 54)
                                                .addComponent(jButton6)
                                                .addGap(28, 28, 28)
                                                .addComponent(jButton5)
                                                .addGap(18, 18, 18)))));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addComponent(jButton5,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jButton6,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addContainerGap(22, Short.MAX_VALUE)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Business Statistic");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\predictive-chart (1).png")); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\sport-car (1).png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jLabel9.setText("35");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel10.setText("Total Cars Available");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout
                                                .createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(jLabel10))
                                        .addGroup(jPanel4Layout
                                                .createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addComponent(jLabel9))
                                        .addGroup(jPanel4Layout
                                                .createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel8)))
                                .addContainerGap(55, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(12, Short.MAX_VALUE)
                                .addComponent(jLabel8,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        66,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44)));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\money-bag (1).png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("156");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Cars Rented This Month");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout
                                                .createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout
                                                                .createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel12))
                                                        .addComponent(jLabel11)))
                                        .addGroup(jPanel5Layout
                                                .createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jLabel13)))
                                .addContainerGap(53, Short.MAX_VALUE)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel11,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addContainerGap(45, Short.MAX_VALUE)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
jPanel4.setPreferredSize(new java.awt.Dimension(250, 150));
jPanel5.setPreferredSize(new java.awt.Dimension(250, 150));
jPanel6.setPreferredSize(new java.awt.Dimension(250, 150));
jPanel7.setPreferredSize(new java.awt.Dimension(450, 200));
jPanel8.setPreferredSize(new java.awt.Dimension(450, 200));

// Set minimum and maximum sizes to ensure consistent heights
jPanel7.setMinimumSize(new java.awt.Dimension(450, 200));
jPanel8.setMinimumSize(new java.awt.Dimension(450, 200));
jPanel7.setMaximumSize(new java.awt.Dimension(450, 200));
jPanel8.setMaximumSize(new java.awt.Dimension(450, 200));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\customer (1).png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("313");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Clients Registered");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout
                                                .createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14)
                                                        .addGroup(jPanel6Layout
                                                                .createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel15))))
                                        .addGroup(jPanel6Layout
                                                .createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(jLabel16)))
                                .addContainerGap(70, Short.MAX_VALUE)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel14)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addContainerGap(50, Short.MAX_VALUE)));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\run (1).png")); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Quick Actions");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Car Management");

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\addition-thick-symbol (1).png")); // NOI18N
        jButton7.setText(" Add New Car");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\pencil (1).png")); // NOI18N
        jButton8.setText("Edit Car Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\remove (1).png")); // NOI18N
        jButton9.setText("Delete Car");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\view-list (1).png")); // NOI18N
        jButton10.setText("List Cars");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel19)
                                .addContainerGap(153, Short.MAX_VALUE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel7Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton9,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jButton7,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                175,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel7Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton8,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                184,
                                                Short.MAX_VALUE)
                                        .addComponent(jButton10,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(17, 17, 17)));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel7Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton7,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton8,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel7Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton9,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(33, Short.MAX_VALUE)));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("Booking & Payment");

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\team-management (2).png")); // NOI18N
        jButton11.setText(" Manage Bookings");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\credit-card (1).png")); // NOI18N
        jButton12.setText(" Process Payment");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\accountant (1).png")); // NOI18N
        jButton13.setText(" View Reports");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setIcon(
                new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\addition-thick-symbol (1).png")); // NOI18N
        jButton14.setText("New Booking");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton11,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        175,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(jButton12,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        175,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout
                                                .createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(jLabel20))
                                        .addGroup(jPanel8Layout
                                                .createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton13,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        175,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(68, 68, 68)
                                                .addComponent(jButton14,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        175,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel8Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton11,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton12,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel8Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton13,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton14,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);

        // Create container panel for centered elements
        JPanel centeredPanel = new JPanel();
        centeredPanel.setOpaque(false);
        centeredPanel.setBackground(new java.awt.Color(255, 153, 0));
        centeredPanel.setLayout(new javax.swing.BoxLayout(centeredPanel, javax.swing.BoxLayout.Y_AXIS));
        
        // Create wrapper panel for the centered content
        JPanel wrapperPanel = new JPanel();
        wrapperPanel.setOpaque(false);
        wrapperPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        centeredPanel.setBackground(new java.awt.Color(255, 153, 0));
        
        // Add components to centered panel with proper alignment
        jLabel7.setAlignmentX(Component.CENTER_ALIGNMENT);
        jLabel6.setAlignmentX(Component.CENTER_ALIGNMENT);
        jLabel17.setAlignmentX(Component.CENTER_ALIGNMENT);
        jLabel18.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        centeredPanel.add(Box.createVerticalGlue());
        centeredPanel.add(jLabel7);
        centeredPanel.add(Box.createVerticalStrut(5));
        centeredPanel.add(jLabel6);
        centeredPanel.add(Box.createVerticalGlue());
        
        wrapperPanel.add(centeredPanel);
        // Create wrapper panel for Quick Actions header
        JPanel quickActionsPanel = new JPanel();
        quickActionsPanel.setOpaque(false);
        quickActionsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        
        JPanel quickActionsContent = new JPanel();
        quickActionsContent.setOpaque(false);
        quickActionsContent.setLayout(new javax.swing.BoxLayout(quickActionsContent, javax.swing.BoxLayout.X_AXIS));
        quickActionsContent.add(jLabel17);
        quickActionsContent.add(Box.createHorizontalStrut(10));
        quickActionsContent.add(jLabel18);
        quickActionsPanel.add(quickActionsContent);

        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wrapperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quickActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(wrapperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(quickActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE)));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sidebarPanel,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        1014, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE,
                                Short.MAX_VALUE));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {
        // Dashboard Button
        if (currentFrame == EmployeeDashboard.class) {
            return;
        }

        this.dispose();
        EmployeeDashboard dash = new EmployeeDashboard(this.currentUser);
        dash.setVisible(true);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Car management button
        if (currentFrame == VehicleManagementForm.class) {
            return;
        }

        this.dispose();
        VehicleManagementForm car = new VehicleManagementForm(currentUser);
        car.setVisible(true);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // Booking management button
        if (currentFrame == BookingManagementForm.class) {
            return;
        }

        this.dispose();
        BookingManagementForm booking = new BookingManagementForm(currentUser);
        booking.setVisible(true);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // Payment management button
        // TODO: Implement payment management form
        JOptionPane.showMessageDialog(this, "Payment Management feature coming soon!");
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate to VehicleManagementForm and trigger add vehicle dialog
        VehicleManagementForm vehicleForm = new VehicleManagementForm();
        vehicleForm.setVisible(true);
        vehicleForm.openAddVehicleDialog();
        this.dispose();
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentUser == null) {
            JOptionPane.showMessageDialog(this,
                    "Error: User session not found. Please log in again.",
                    "Session Error",
                    JOptionPane.ERROR_MESSAGE);
            // Redirect to login
            this.dispose();
            LoginForm login = new LoginForm();
            login.setVisible(true);
            return;
        }
        // TODO: Create EmployeeProfile form
        JOptionPane.showMessageDialog(this, "Employee Profile feature coming soon!");
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        VehicleManagementForm vehicleForm = new VehicleManagementForm();
        vehicleForm.setVisible(true);
        vehicleForm.openEditVehicleDialog();
        this.dispose();
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        VehicleManagementForm vehicleForm = new VehicleManagementForm();
        vehicleForm.setVisible(true);
        vehicleForm.deleteSelectedVehicle();
        this.dispose();
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
        ListCars listCars = new ListCars(currentUser);
        listCars.setVisible(true);
        // this.dispose();
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
        // Manage Bookings button
        BookingManagementForm bookingForm = new BookingManagementForm(currentUser);
        bookingForm.setVisible(true);
    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
        // Process Payment button
        JOptionPane.showMessageDialog(this, "Payment Processing feature coming soon!");
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
        // View Reports button
        JOptionPane.showMessageDialog(this, "Reports feature coming soon!");
    }

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
        // New Booking button
        // TODO: Implement new booking dialog
        JOptionPane.showMessageDialog(this, "New Booking feature coming soon!");
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }

    private void updateAvailableVehiclesCount() {
        int availableVehicles = vehicleController.loadAllVehicles().size();
        jLabel9.setText(String.valueOf(availableVehicles));
    }

    private void updateRentedCarsCount() {
        int rentedCars = vehicleController.getRentedVehicles().size();
        jLabel12.setText(String.valueOf(rentedCars));
    }

    private void updateCustomersCount() {
        int customers = customerController.getAllCustomers().size();
        jLabel15.setText(String.valueOf(customers));
    }

    // Removed booking table and related methods as they are no longer needed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
