package vehiclerentalsystem.GUI;

import vehiclerentalsystem.Controllers.VehicleController;
import vehiclerentalsystem.Models.Vehicle;
import vehiclerentalsystem.Utils.WrapLayout;
import java.awt.*;
import java.util.List;
import javax.swing.*;

public class VehicleManagementForm extends javax.swing.JFrame {

    private Class<?> currentFrame;
    private VehicleController vehicleController;
    private JPanel cardsPanel;
    private JScrollPane cardsScrollPane;
    private JPanel headerPanel;
    
    public VehicleManagementForm() {
        vehicleController = new VehicleController();
        initComponents();
        currentFrame = this.getClass();
        setupMainContent();
        loadVehicles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Management");
        setPreferredSize(new java.awt.Dimension(1200, 800));

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 0));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\sport-car (2).png")); // NOI18N
        jLabel1.setText(" CarRental Admin");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 5));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\house (2).png")); // NOI18N
        jButton1.setText(" DashBoard");
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\sport-car (2).png")); // NOI18N
        jButton2.setText(" Car Management");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\accountant (1).png")); // NOI18N
        jButton3.setText(" Employee Managment");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });


        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhd\\Downloads\\settings (1).png")); // NOI18N
        jButton4.setText(" Settings");
        jButton4.setBorderPainted(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidebarPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton3)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 657, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }

    private void setupMainContent() {
        // Update the main layout to BorderLayout
        getContentPane().setLayout(new BorderLayout());
        
        // Add sidebar to WEST
        getContentPane().add(sidebarPanel, BorderLayout.WEST);
        
        // Create main content panel
        JPanel mainContentPanel = new JPanel(new BorderLayout());
        mainContentPanel.setBackground(new Color(245, 245, 245));
        
        // Create header panel with buttons
        headerPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 15));
        headerPanel.setBackground(Color.WHITE);
        headerPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Create action buttons
        JButton addButton = createHeaderButton("Add Vehicle", new Color(39, 174, 96));
        JButton editButton = createHeaderButton("Edit Vehicle", new Color(52, 152, 219));
        JButton deleteButton = createHeaderButton("Delete Vehicle", new Color(231, 76, 60));
        JButton refreshButton = createHeaderButton("Refresh", new Color(149, 165, 166));
        
        // Add action listeners
        addButton.addActionListener(e -> openAddVehicleDialog());
        editButton.addActionListener(e -> openEditVehicleDialog());
        deleteButton.addActionListener(e -> deleteSelectedVehicle());
        refreshButton.addActionListener(e -> loadVehicles());
        
        headerPanel.add(addButton);
        headerPanel.add(editButton);
        headerPanel.add(deleteButton);
        headerPanel.add(refreshButton);
        
        // Create cards panel with WrapLayout for grid-like flow
        cardsPanel = new JPanel(new WrapLayout(FlowLayout.LEFT, 25, 25));
        cardsPanel.setBackground(new Color(245, 245, 245));
        
        // Create scroll pane for cards
        cardsScrollPane = new JScrollPane(cardsPanel);
        cardsScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        cardsScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        cardsScrollPane.setBorder(null);
        cardsScrollPane.getVerticalScrollBar().setUnitIncrement(16); // Smooth scrolling
        
        // Add components to main content
        mainContentPanel.add(headerPanel, BorderLayout.NORTH);
        mainContentPanel.add(cardsScrollPane, BorderLayout.CENTER);
        
        // Add main content to frame
        getContentPane().add(mainContentPanel, BorderLayout.CENTER);
    }
    
    private JButton createHeaderButton(String text, Color backgroundColor) {
        JButton button = new JButton(text);
        button.setBackground(backgroundColor);
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Segoe UI", Font.BOLD, 12));
        button.setPreferredSize(new Dimension(120, 35));
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return button;
    }
    
    private void loadVehicles() {
        // Clear existing cards
        cardsPanel.removeAll();
        
        // Load vehicles from controller
        List<Vehicle> vehicles = vehicleController.loadAllVehicles();
        
        if (vehicles.isEmpty()) {
            JLabel noVehiclesLabel = new JLabel("No vehicles found. Click 'Add Vehicle' to get started.");
            noVehiclesLabel.setFont(new Font("Segoe UI", Font.PLAIN, 16));
            noVehiclesLabel.setForeground(Color.GRAY);
            cardsPanel.add(noVehiclesLabel);
        } else {
            // Create card for each vehicle
            for (Vehicle vehicle : vehicles) {
                CarCard carCard = new CarCard(vehicle);
                // Set preferred size for the card to control its dimensions
                // Card size is now controlled by CarCard component
                cardsPanel.add(carCard);
            }
        }
        
        // Refresh the display
        cardsPanel.revalidate();
        cardsPanel.repaint();
    }
    
    private void showAddVehicleDialog() {
        AddEditVehicleDialog dialog = new AddEditVehicleDialog(this, null, vehicleController);
        dialog.setVisible(true);
        
        // Refresh vehicles after dialog closes
        loadVehicles();
    }
    
    public void openAddVehicleDialog() {
        showAddVehicleDialog();
    }
    
    public void openEditVehicleDialog() {
         CarCard selectedCard = null;
        for (Component comp : cardsPanel.getComponents()) {
            if (comp instanceof CarCard) {
                CarCard card = (CarCard) comp;
                if (card.isSelected()) {
                    selectedCard = card;
                    break;
                }
            }
        }
        
        if (selectedCard == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a vehicle to edit.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to edit this vehicle?\n" +
            "Brand: " + selectedCard.getVehicle().getBrand() + "\n" +
            "Model: " + selectedCard.getVehicle().getModel() + "\n" +
            "Plate: " + selectedCard.getVehicle().getPlateNb(),
            "Confirm Edit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if(confirm == JOptionPane.YES_OPTION) {
            try {
                // edit the vehicle using controller
                AddEditVehicleDialog dialog= new AddEditVehicleDialog(this, selectedCard.getVehicle(), vehicleController);
                dialog.setVisible(true);
                loadVehicles();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "An error occurred while editing the vehicle: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public void deleteSelectedVehicle() {
        // Find selected vehicle card
        CarCard selectedCard = null;
        for (Component comp : cardsPanel.getComponents()) {
            if (comp instanceof CarCard) {
                CarCard card = (CarCard) comp;
                if (card.isSelected()) {
                    selectedCard = card;
                    break;
                }
            }
        }
        
        if (selectedCard == null) {
            JOptionPane.showMessageDialog(this,
                "Please select a vehicle to delete.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this vehicle?\n" +
            "Brand: " + selectedCard.getVehicle().getBrand() + "\n" +
            "Model: " + selectedCard.getVehicle().getModel() + "\n" +
            "Plate: " + selectedCard.getVehicle().getPlateNb(),
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
            
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Delete the vehicle using controller
                boolean deleted = vehicleController.removeVehicle(selectedCard.getVehicle().getId());
                if (deleted) {
                    JOptionPane.showMessageDialog(this,
                        "Vehicle deleted successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    // Refresh the vehicle list
                    loadVehicles();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Failed to delete the vehicle. Please try again.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "An error occurred while deleting the vehicle: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // DashBoard Button
        if (currentFrame == AdminDashboard.class){
            return;
        }
        
        this.dispose();
        AdminDashboard dash = new AdminDashboard();
        dash.setVisible(true);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Car management button
        if (currentFrame == VehicleManagementForm.class){
            return;
        }
        
        this.dispose();
        VehicleManagementForm car = new VehicleManagementForm();
        car.setVisible(true);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentFrame == EmployeeManagementForm.class){
            return;
        }
        
        this.dispose();
        EmployeeManagementForm employee = new EmployeeManagementForm();
        employee.setVisible(true);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {


    }



    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}